import { readFile, access, stat } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
const root = new URL('../', import.meta.url);
const read = path => readFile(new URL(path, root), 'utf8');
const bytes = path => readFile(new URL(path, root));
const assert = (condition, message) => { if (!condition) throw new Error(message); };
const exists = async path => access(fileURLToPath(new URL(path, root)));
const paths={recruiter:'index.html',resume:'resume/index.html',master:'master/index.html',mesh:'mesh/index.html',machine:'machine/index.html',css:'assets/site.css',cssSystems:'assets/site.systems.css',portfolio:'data/portfolio.json',companies:'data/company-families.json',profiles:'data/psysoc-x-profiles.json',vercel:'vercel.json',pdf:'downloads/Casey_Barton_Resume.pdf',social:'assets/social-card.svg',favicon:'assets/favicon.svg',sitemap:'sitemap.xml',robots:'robots.txt',llms:'llms.txt',notFound:'404.html'};
for(const p of Object.values(paths)) await exists(p);
const [recruiter,resume,master,mesh,machine,cssBase,cssSystems,portfolioText,companiesText,profilesText,vercelText,sitemap,robots,llms]=await Promise.all([read(paths.recruiter),read(paths.resume),read(paths.master),read(paths.mesh),read(paths.machine),read(paths.css),read(paths.cssSystems),read(paths.portfolio),read(paths.companies),read(paths.profiles),read(paths.vercel),read(paths.sitemap),read(paths.robots),read(paths.llms)]);
const css=cssBase+'\n'+cssSystems;
const portfolio=JSON.parse(portfolioText),companies=JSON.parse(companiesText),profiles=JSON.parse(profilesText),vercel=JSON.parse(vercelText);
const pages={recruiter,resume,master,mesh,machine};
for(const [name,html] of Object.entries(pages)){
  assert((html.match(/<h1\b/g)||[]).length===1,`${name} must contain one h1`);
  assert(!html.includes('<script'),`${name} must remain script-free`);
  assert(!html.includes('javascript:'),`${name} cannot use javascript URLs`);
  assert(!html.includes('style='),`${name} cannot use inline style attributes`);
  assert(html.includes('href="/assets/site.css"'),`${name} must use base CSS`);
  assert(html.includes('href="/assets/site.systems.css"'),`${name} must use systems CSS`);
  assert(html.includes('Casey Barton')||html.includes('Casey Del Carpio Barton'),`${name} identity missing`);
}
assert(portfolio.schema==='glaciereq.hiring-portfolio.v15','portfolio schema drift');
assert(portfolio.person.name==='Casey Del Carpio Barton','name drift');
assert(portfolio.proof.receipt_router_tests===69,'router count drift');
assert(portfolio.proof.bounded_source_tests===166,'source count drift');
assert(portfolio.proof.energy_memory_tests===19,'memory count drift');
assert(portfolio.proof.external_actions===0,'external action drift');
assert(portfolio.proof.receipt_router_artifact===8910423397,'artifact drift');
assert(portfolio.flagships.length===10,'ten flagships required');
assert(portfolio.flagships[0].id==='receipt-router','router must rank first');
assert(portfolio.flagships[1].id==='microcode'&&portfolio.flagships[1].state==='REVIEWED_EXECUTION_BLOCKED','Microcode boundary drift');
for(const token of ['69/69','166','19','>0<','Portfolio Receipt Router','Microcode Governance','I make powerful AI <em>dependable enough to use.</em>']) assert(recruiter.includes(token),`recruiter missing ${token}`);
assert(recruiter.includes('cockpit')&&recruiter.includes('bento')&&recruiter.includes('pipeline'),'cutting-edge visual hierarchy missing');
assert(recruiter.indexOf('Portfolio Receipt Router')<recruiter.indexOf('Microcode Governance'),'verified work must precede pending work');
for(const route of ['/master/','/mesh/','/machine/','/resume/']) assert(recruiter.includes(`href="${route}"`),`route missing ${route}`);
assert(resume.includes('/downloads/Casey_Barton_Resume.pdf')&&resume.includes('RESUME_ATS.md'),'resume downloads missing');
assert(resume.includes('69/69')&&resume.includes('166 source tests')&&resume.includes('148/148'),'resume proof drift');
assert(master.toLowerCase().includes('69 of 69 tests passed')&&master.includes('166')&&master.includes('19 memory tests'),'master evidence incomplete');
assert(master.includes('Owning repositories retain evidence authority') || master.includes('Proof stays with the owning system'),'master evidence policy missing');
assert(machine.includes('/data/portfolio.json')&&machine.includes('/data/company-families.json')&&machine.includes('/data/psysoc-x-profiles.json'),'machine links incomplete');
assert(companies.schema==='glaciereq.public-company-mesh.v15','company schema drift');
assert(companies.families.length===27&&companies.totals.unique_repositories===200&&companies.totals.memberships===203,'company totals drift');
for(const family of companies.families) assert(mesh.includes(`<h3>${family.name}</h3>`),`mesh missing ${family.name}`);
assert(profiles.schema==='glaciereq.psysoc-x.presentation-profiles.v15','profile schema drift');
assert(Object.keys(profiles.profiles).sort().join(',')==='machine,master,mesh,recruiter','four profiles required');
assert(profiles.invariants.includes('test_counts')&&profiles.invariants.includes('authority_boundaries'),'invariants incomplete');
assert(Object.values(profiles.safety).every(v=>v===false),'safety exclusions must remain false');
const csp=vercel.headers?.[0]?.headers?.find(x=>x.key==='Content-Security-Policy')?.value??'';
assert(csp.includes("script-src 'none'")&&csp.includes("style-src 'self'")&&csp.includes("connect-src 'none'")&&csp.includes("frame-ancestors 'none'"),'CSP incomplete');
for(const token of ['.cockpit','.radar','.bento','.terminal','@keyframes spin','@media(prefers-reduced-motion:reduce)','@media print']) assert(css.includes(token),`CSS contract missing ${token}`);
assert(css.length>18000,'visual system unexpectedly small');
for(const route of ['/','/resume/','/master/','/mesh/','/machine/']) assert(sitemap.includes(`https://casey-barton-glaciereq.vercel.app${route}`),`sitemap missing ${route}`);
assert(robots.includes('Sitemap: https://casey-barton-glaciereq.vercel.app/sitemap.xml'),'robots missing sitemap');
assert(llms.includes('/data/portfolio.json')&&llms.includes('/data/psysoc-x-profiles.json'),'LLM orientation incomplete');
const pdf=await bytes(paths.pdf); assert(pdf.subarray(0,4).toString()==='%PDF','PDF signature invalid'); assert((await stat(fileURLToPath(new URL(paths.pdf,root)))).size>8000,'PDF too small');
console.log(JSON.stringify({status:'PASS',release:'V16 Signal Architecture',routes:['/','/resume/','/master/','/mesh/','/machine/'],profiles:Object.keys(profiles.profiles),facts_invariant:true,proof:portfolio.proof,flagships:10,company_families:27,repositories:200,scripts:0,inline_styles:0,visual_contracts:['cockpit','radar','bento','terminal','CSS motion','reduced motion','print'],csp:'locked'},null,2));
